#
# From:
# https://github.com/BamPeers/rust-ci-github-actions-workflow
# Specially:
# https://github.com/BamPeers/rust-ci-github-actions-workflow/blob/main/.github/workflows/release-packaging.yaml
#
on:
  push:
    branches:
      - main
      - master
name: Release Packaging
jobs:
  release:
    name: Release Packaging
    env:
      PROJECT_NAME_UNDERSCORE: rdotenv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Release Build
        run: cargo build --release
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME_UNDERSCORE }}
          path: target/release/${{ env.PROJECT_NAME_UNDERSCORE }}
